services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.3
    container_name: keycloak-lab
    ports:
      - "7080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: start-dev
