= Apache Kafka

Apache Kafka is an open-source distributed event streaming platform used by thousands of companies for high-performance data pipelines, streaming analytics, data integration, and mission-critical applications.

* *High Throughput*: Deliver messages at network limited throughput using a cluster of machines with latencies as low as 2ms.
* *Scalable*: Scale production clusters up to a thousand brokers, trillions of messages per day, petabytes of data, hundreds of thousands of partitions. Elastically expand and contract storage and processing.
* *Permanent storage*: Store streams of data safely in a distributed, durable, fault-tolerant cluster.
* *High availability*: Stretch clusters efficiently over availability zones or connect separate clusters across geographic regions.

== Good to know

=== No Zookeeper needed anymore

Apache Kafka® Raft (KRaft) is the consensus protocol that was introduced to remove Kafka’s dependency on ZooKeeper for metadata management. This greatly simplifies Kafka’s architecture by consolidating responsibility for metadata into Kafka itself, rather than requiring and configuring two different systems: ZooKeeper and Kafka. https://docs.confluent.io/platform/current/kafka-metadata/kraft.html[source]

== Lab

Quickstart

    cd ./lab/docker
    docker compose up -d

Services

* https://kafka.apache.org/[Apache Kafka]
* https://github.com/provectus/kafka-ui[kafka-ui]
